name = "Horror Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5383d564d7a48f92e06d73d048f3cb2d778162517227ef58faf5f4787b34527a"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
