name = "Horror Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "357ab48451b9327ce0aab3762ca7062096160768a9ed018e27bafc0be5625dc3"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
