name = "Horror Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7fef046e32ab5c1fb8cfe1c262b3463a8b38fc41cff1799177f99c7e7be924d9"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
