name = "Horror Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f548c13299c34795cc09777b55421ebffdc53619d5ed3a7495e4a81f64dce30"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
