name = "Horror Pack"
author = "tjamesw123"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "72eaf5ddaff70af922707e824d450da553b7a707d10c364c842ca82ed0c49c3c"

[versions]
fabric = "0.15.11"
minecraft = "1.19.2"
